[colors]
[colors.primary]
background = "#1d222c"
foreground = "#ffffff"

[colors.normal]
black   = "#1d222c"
red     = "#E8D5BC"
green   = "#BDC1B9"
yellow  = "#D5D0C4"
blue    = "#9ba7ba"
magenta = "#8fa0b5"
cyan    = "#93adc2
white   = "#a4c2c7

[colors.bright]
black   = "#595f6c"
red     = "#ffb3a7"
green   = "#c7e9c0"
yellow  = "#fff2ae"
blue    = "#a8c7e8"
magenta = "#c8a7e6"
cyan    = "#a9e1dd"
white   = "#f7f9fc"

[colors.cursor]
text   = "#1d222c"
cursor = "#ffffff"
