accent = "#9ba7ba"
cursor = "#ffffff"
foreground = "#ffffff"
background = "#1d222c"
selection_foreground = "#ffffff"
selection_background = "#9ba7ba"

color0 = "#1d222c"
color1 = "#E8D5BC"
color2 = "#BDC1B9"
color3 = "#D5D0C4"
color4 = "#9ba7ba"
color5 = "#8fa0b5"
color6 = "#93adc2"
color7 = "#a4c2c7"
color8 = "#595f6c"
color9 = "#ffb3a7"
color10 = "#c7e9c0"
color11 = "#fff2ae"
color12 = "#a8c7e8"
color13 = "#c8a7e6"
color14 = "#a9e1dd"
color15 = "#f7f9fc"
